[workspace.package]
version = "0.1.0"
edition = "2021"
authors = [
    "Yuanchang Xu <yuanchang.xu@outlook.com>"
]
license = "MIT/Apache-2.0"

[workspace]
members = [
    "proto",
    "core",
    "oceanraft",
    "oceanraft/harness"
]